
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.kraftmine.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.RegisterColorHandlersEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import net.mcreator.kraftmine.block.XPBankBlock;
import net.mcreator.kraftmine.block.WallnutBlock;
import net.mcreator.kraftmine.block.WallBlockBlock;
import net.mcreator.kraftmine.block.TungstenOreBlock;
import net.mcreator.kraftmine.block.TungstenBlockBlock;
import net.mcreator.kraftmine.block.TomatoBushBlock;
import net.mcreator.kraftmine.block.TomatoBush3Block;
import net.mcreator.kraftmine.block.TomatoBush2Block;
import net.mcreator.kraftmine.block.TomatoBush1Block;
import net.mcreator.kraftmine.block.TitaniumOreBlock;
import net.mcreator.kraftmine.block.TitaniumBlockBlock;
import net.mcreator.kraftmine.block.SupplyCrateBlock;
import net.mcreator.kraftmine.block.SaphhireOreBlock;
import net.mcreator.kraftmine.block.SaphhireBlockBlock;
import net.mcreator.kraftmine.block.RubyOreBlock;
import net.mcreator.kraftmine.block.RubyBlockBlock;
import net.mcreator.kraftmine.block.PlasticOreBlock;
import net.mcreator.kraftmine.block.PlasticBlockBlock;
import net.mcreator.kraftmine.block.PalmWoodWoodBlock;
import net.mcreator.kraftmine.block.PalmWoodStairsBlock;
import net.mcreator.kraftmine.block.PalmWoodSlabBlock;
import net.mcreator.kraftmine.block.PalmWoodPressurePlateBlock;
import net.mcreator.kraftmine.block.PalmWoodPlanksBlock;
import net.mcreator.kraftmine.block.PalmWoodLogBlock;
import net.mcreator.kraftmine.block.PalmWoodLeavesBlock;
import net.mcreator.kraftmine.block.PalmWoodFenceGateBlock;
import net.mcreator.kraftmine.block.PalmWoodFenceBlock;
import net.mcreator.kraftmine.block.PalmWoodButtonBlock;
import net.mcreator.kraftmine.block.NickelOreBlock;
import net.mcreator.kraftmine.block.NickelBlockBlock;
import net.mcreator.kraftmine.block.MoltenObsidianBlock;
import net.mcreator.kraftmine.block.MilkBucketBlock;
import net.mcreator.kraftmine.block.MahoganyWoodBlock;
import net.mcreator.kraftmine.block.MahoganyStairsBlock;
import net.mcreator.kraftmine.block.MahoganySlabBlock;
import net.mcreator.kraftmine.block.MahoganyPressurePlateBlock;
import net.mcreator.kraftmine.block.MahoganyPlanksBlock;
import net.mcreator.kraftmine.block.MahoganyLogBlock;
import net.mcreator.kraftmine.block.MahoganyLeavesBlock;
import net.mcreator.kraftmine.block.MahoganyFenceGateBlock;
import net.mcreator.kraftmine.block.MahoganyFenceBlock;
import net.mcreator.kraftmine.block.MahoganyButtonBlock;
import net.mcreator.kraftmine.block.LuckyBlockBlock;
import net.mcreator.kraftmine.block.LifeOrbBlock;
import net.mcreator.kraftmine.block.LegoBlockBlock;
import net.mcreator.kraftmine.block.IrisSilverBlock;
import net.mcreator.kraftmine.block.IrisPurpleBlock;
import net.mcreator.kraftmine.block.GravityDisruptorBlock;
import net.mcreator.kraftmine.block.GoldenAppleBlockBlock;
import net.mcreator.kraftmine.block.GlowShroomBlock;
import net.mcreator.kraftmine.block.FireflyLanternBlock;
import net.mcreator.kraftmine.block.EmptyLanternBlock;
import net.mcreator.kraftmine.block.DriedLeavesBlock;
import net.mcreator.kraftmine.block.DomainBarrierBlock;
import net.mcreator.kraftmine.block.DeepslateTungstenOreBlock;
import net.mcreator.kraftmine.block.DeepslateTitaniumOreBlock;
import net.mcreator.kraftmine.block.DeadwoodWoodBlock;
import net.mcreator.kraftmine.block.DeadwoodStairsBlock;
import net.mcreator.kraftmine.block.DeadwoodSlabBlock;
import net.mcreator.kraftmine.block.DeadwoodPressurePlateBlock;
import net.mcreator.kraftmine.block.DeadwoodPlanksBlock;
import net.mcreator.kraftmine.block.DeadwoodLogBlock;
import net.mcreator.kraftmine.block.DeadwoodLeavesBlock;
import net.mcreator.kraftmine.block.DeadwoodFenceGateBlock;
import net.mcreator.kraftmine.block.DeadwoodFenceBlock;
import net.mcreator.kraftmine.block.DeadwoodButtonBlock;
import net.mcreator.kraftmine.block.CornCrop2Block;
import net.mcreator.kraftmine.block.CornCrop1Block;
import net.mcreator.kraftmine.block.CornCrop0Block;
import net.mcreator.kraftmine.block.CoconutBlockBlock;
import net.mcreator.kraftmine.block.CoarseGrassBlockBlock;
import net.mcreator.kraftmine.block.CloudSapphireOreBlock;
import net.mcreator.kraftmine.block.CloudRubyOreBlock;
import net.mcreator.kraftmine.block.CloudBlockRainBlock;
import net.mcreator.kraftmine.block.CloudBlock;
import net.mcreator.kraftmine.block.ChillIceBlock;
import net.mcreator.kraftmine.block.CherryWoodBlock;
import net.mcreator.kraftmine.block.CherryStairsBlock;
import net.mcreator.kraftmine.block.CherrySlabBlock;
import net.mcreator.kraftmine.block.CherryPressurePlateBlock;
import net.mcreator.kraftmine.block.CherryPlanksBlock;
import net.mcreator.kraftmine.block.CherryLogBlock;
import net.mcreator.kraftmine.block.CherryLeavesBlock;
import net.mcreator.kraftmine.block.CherryFenceGateBlock;
import net.mcreator.kraftmine.block.CherryFenceBlock;
import net.mcreator.kraftmine.block.CherryButtonBlock;
import net.mcreator.kraftmine.block.CanSuspiciousStewBlock;
import net.mcreator.kraftmine.block.CanRabbitStewBlock;
import net.mcreator.kraftmine.block.CanMushroomStewBlock;
import net.mcreator.kraftmine.block.CanBreadBlock;
import net.mcreator.kraftmine.block.CanBeansBlock;
import net.mcreator.kraftmine.block.BambooStairsBlock;
import net.mcreator.kraftmine.block.BambooSlabBlock;
import net.mcreator.kraftmine.block.BambooPressurePlateBlock;
import net.mcreator.kraftmine.block.BambooPlanksBlock;
import net.mcreator.kraftmine.block.BambooFenceGateBlock;
import net.mcreator.kraftmine.block.BambooFenceBlock;
import net.mcreator.kraftmine.block.BambooButtonBlock;
import net.mcreator.kraftmine.block.BackroomTriggered2Block;
import net.mcreator.kraftmine.block.BackroomTriggerBlock;
import net.mcreator.kraftmine.block.AppleblockBlock;
import net.mcreator.kraftmine.block.AluminumOreBlock;
import net.mcreator.kraftmine.block.AluminumBlockBlock;
import net.mcreator.kraftmine.block.AetherancientdebrisBlock;
import net.mcreator.kraftmine.block.AetherPortalBlock;
import net.mcreator.kraftmine.block.AcidBlock;
import net.mcreator.kraftmine.KraftmineMod;

public class KraftmineModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, KraftmineMod.MODID);
	public static final RegistryObject<Block> MAHOGANY_WOOD = REGISTRY.register("mahogany_wood", () -> new MahoganyWoodBlock());
	public static final RegistryObject<Block> MAHOGANY_LOG = REGISTRY.register("mahogany_log", () -> new MahoganyLogBlock());
	public static final RegistryObject<Block> MAHOGANY_PLANKS = REGISTRY.register("mahogany_planks", () -> new MahoganyPlanksBlock());
	public static final RegistryObject<Block> MAHOGANY_LEAVES = REGISTRY.register("mahogany_leaves", () -> new MahoganyLeavesBlock());
	public static final RegistryObject<Block> MAHOGANY_STAIRS = REGISTRY.register("mahogany_stairs", () -> new MahoganyStairsBlock());
	public static final RegistryObject<Block> MAHOGANY_SLAB = REGISTRY.register("mahogany_slab", () -> new MahoganySlabBlock());
	public static final RegistryObject<Block> MAHOGANY_FENCE = REGISTRY.register("mahogany_fence", () -> new MahoganyFenceBlock());
	public static final RegistryObject<Block> MAHOGANY_FENCE_GATE = REGISTRY.register("mahogany_fence_gate", () -> new MahoganyFenceGateBlock());
	public static final RegistryObject<Block> MAHOGANY_PRESSURE_PLATE = REGISTRY.register("mahogany_pressure_plate", () -> new MahoganyPressurePlateBlock());
	public static final RegistryObject<Block> MAHOGANY_BUTTON = REGISTRY.register("mahogany_button", () -> new MahoganyButtonBlock());
	public static final RegistryObject<Block> CHERRY_WOOD = REGISTRY.register("cherry_wood", () -> new CherryWoodBlock());
	public static final RegistryObject<Block> CHERRY_LOG = REGISTRY.register("cherry_log", () -> new CherryLogBlock());
	public static final RegistryObject<Block> CHERRY_PLANKS = REGISTRY.register("cherry_planks", () -> new CherryPlanksBlock());
	public static final RegistryObject<Block> CHERRY_LEAVES = REGISTRY.register("cherry_leaves", () -> new CherryLeavesBlock());
	public static final RegistryObject<Block> CHERRY_STAIRS = REGISTRY.register("cherry_stairs", () -> new CherryStairsBlock());
	public static final RegistryObject<Block> CHERRY_SLAB = REGISTRY.register("cherry_slab", () -> new CherrySlabBlock());
	public static final RegistryObject<Block> CHERRY_FENCE_GATE = REGISTRY.register("cherry_fence_gate", () -> new CherryFenceGateBlock());
	public static final RegistryObject<Block> CHERRY_BUTTON = REGISTRY.register("cherry_button", () -> new CherryButtonBlock());
	public static final RegistryObject<Block> PALM_WOOD_WOOD = REGISTRY.register("palm_wood_wood", () -> new PalmWoodWoodBlock());
	public static final RegistryObject<Block> PALM_WOOD_LOG = REGISTRY.register("palm_wood_log", () -> new PalmWoodLogBlock());
	public static final RegistryObject<Block> PALM_WOOD_PLANKS = REGISTRY.register("palm_wood_planks", () -> new PalmWoodPlanksBlock());
	public static final RegistryObject<Block> PALM_WOOD_LEAVES = REGISTRY.register("palm_wood_leaves", () -> new PalmWoodLeavesBlock());
	public static final RegistryObject<Block> PALM_WOOD_STAIRS = REGISTRY.register("palm_wood_stairs", () -> new PalmWoodStairsBlock());
	public static final RegistryObject<Block> PALM_WOOD_SLAB = REGISTRY.register("palm_wood_slab", () -> new PalmWoodSlabBlock());
	public static final RegistryObject<Block> PALM_WOOD_FENCE = REGISTRY.register("palm_wood_fence", () -> new PalmWoodFenceBlock());
	public static final RegistryObject<Block> PALM_WOOD_PRESSURE_PLATE = REGISTRY.register("palm_wood_pressure_plate", () -> new PalmWoodPressurePlateBlock());
	public static final RegistryObject<Block> PALM_WOOD_BUTTON = REGISTRY.register("palm_wood_button", () -> new PalmWoodButtonBlock());
	public static final RegistryObject<Block> BAMBOO_PLANKS = REGISTRY.register("bamboo_planks", () -> new BambooPlanksBlock());
	public static final RegistryObject<Block> BAMBOO_STAIRS = REGISTRY.register("bamboo_stairs", () -> new BambooStairsBlock());
	public static final RegistryObject<Block> BAMBOO_SLAB = REGISTRY.register("bamboo_slab", () -> new BambooSlabBlock());
	public static final RegistryObject<Block> BAMBOO_FENCE = REGISTRY.register("bamboo_fence", () -> new BambooFenceBlock());
	public static final RegistryObject<Block> BAMBOO_FENCE_GATE = REGISTRY.register("bamboo_fence_gate", () -> new BambooFenceGateBlock());
	public static final RegistryObject<Block> BAMBOO_PRESSURE_PLATE = REGISTRY.register("bamboo_pressure_plate", () -> new BambooPressurePlateBlock());
	public static final RegistryObject<Block> BAMBOO_BUTTON = REGISTRY.register("bamboo_button", () -> new BambooButtonBlock());
	public static final RegistryObject<Block> APPLEBLOCK = REGISTRY.register("appleblock", () -> new AppleblockBlock());
	public static final RegistryObject<Block> TUNGSTEN_ORE = REGISTRY.register("tungsten_ore", () -> new TungstenOreBlock());
	public static final RegistryObject<Block> TUNGSTEN_BLOCK = REGISTRY.register("tungsten_block", () -> new TungstenBlockBlock());
	public static final RegistryObject<Block> CLOUD = REGISTRY.register("cloud", () -> new CloudBlock());
	public static final RegistryObject<Block> CLOUD_BLOCK_RAIN = REGISTRY.register("cloud_block_rain", () -> new CloudBlockRainBlock());
	public static final RegistryObject<Block> CLOUD_SAPPHIRE_ORE = REGISTRY.register("cloud_sapphire_ore", () -> new CloudSapphireOreBlock());
	public static final RegistryObject<Block> CLOUD_RUBY_ORE = REGISTRY.register("cloud_ruby_ore", () -> new CloudRubyOreBlock());
	public static final RegistryObject<Block> AETHERANCIENTDEBRIS = REGISTRY.register("aetherancientdebris", () -> new AetherancientdebrisBlock());
	public static final RegistryObject<Block> LEGO_BLOCK = REGISTRY.register("lego_block", () -> new LegoBlockBlock());
	public static final RegistryObject<Block> CHERRY_FENCE = REGISTRY.register("cherry_fence", () -> new CherryFenceBlock());
	public static final RegistryObject<Block> CHERRY_PRESSURE_PLATE = REGISTRY.register("cherry_pressure_plate", () -> new CherryPressurePlateBlock());
	public static final RegistryObject<Block> PALM_WOOD_FENCE_GATE = REGISTRY.register("palm_wood_fence_gate", () -> new PalmWoodFenceGateBlock());
	public static final RegistryObject<Block> NICKEL_ORE = REGISTRY.register("nickel_ore", () -> new NickelOreBlock());
	public static final RegistryObject<Block> NICKEL_BLOCK = REGISTRY.register("nickel_block", () -> new NickelBlockBlock());
	public static final RegistryObject<Block> ALUMINUM_ORE = REGISTRY.register("aluminum_ore", () -> new AluminumOreBlock());
	public static final RegistryObject<Block> ALUMINUM_BLOCK = REGISTRY.register("aluminum_block", () -> new AluminumBlockBlock());
	public static final RegistryObject<Block> DEEPSLATE_TUNGSTEN_ORE = REGISTRY.register("deepslate_tungsten_ore", () -> new DeepslateTungstenOreBlock());
	public static final RegistryObject<Block> TITANIUM_ORE = REGISTRY.register("titanium_ore", () -> new TitaniumOreBlock());
	public static final RegistryObject<Block> TITANIUM_BLOCK = REGISTRY.register("titanium_block", () -> new TitaniumBlockBlock());
	public static final RegistryObject<Block> DEEPSLATE_TITANIUM_ORE = REGISTRY.register("deepslate_titanium_ore", () -> new DeepslateTitaniumOreBlock());
	public static final RegistryObject<Block> RUBY_ORE = REGISTRY.register("ruby_ore", () -> new RubyOreBlock());
	public static final RegistryObject<Block> RUBY_BLOCK = REGISTRY.register("ruby_block", () -> new RubyBlockBlock());
	public static final RegistryObject<Block> SAPHHIRE_ORE = REGISTRY.register("saphhire_ore", () -> new SaphhireOreBlock());
	public static final RegistryObject<Block> SAPHHIRE_BLOCK = REGISTRY.register("saphhire_block", () -> new SaphhireBlockBlock());
	public static final RegistryObject<Block> WALL_BLOCK = REGISTRY.register("wall_block", () -> new WallBlockBlock());
	public static final RegistryObject<Block> GRAVITY_DISRUPTOR = REGISTRY.register("gravity_disruptor", () -> new GravityDisruptorBlock());
	public static final RegistryObject<Block> GOLDEN_APPLE_BLOCK = REGISTRY.register("golden_apple_block", () -> new GoldenAppleBlockBlock());
	public static final RegistryObject<Block> AETHER_PORTAL = REGISTRY.register("aether_portal", () -> new AetherPortalBlock());
	public static final RegistryObject<Block> LIFE_ORB = REGISTRY.register("life_orb", () -> new LifeOrbBlock());
	public static final RegistryObject<Block> XP_BANK = REGISTRY.register("xp_bank", () -> new XPBankBlock());
	public static final RegistryObject<Block> MILK_BUCKET = REGISTRY.register("milk_bucket", () -> new MilkBucketBlock());
	public static final RegistryObject<Block> LUCKY_BLOCK = REGISTRY.register("lucky_block", () -> new LuckyBlockBlock());
	public static final RegistryObject<Block> BACKROOM_TRIGGERED_2 = REGISTRY.register("backroom_triggered_2", () -> new BackroomTriggered2Block());
	public static final RegistryObject<Block> DOMAIN_BARRIER = REGISTRY.register("domain_barrier", () -> new DomainBarrierBlock());
	public static final RegistryObject<Block> CHILL_ICE = REGISTRY.register("chill_ice", () -> new ChillIceBlock());
	public static final RegistryObject<Block> SUPPLY_CRATE = REGISTRY.register("supply_crate", () -> new SupplyCrateBlock());
	public static final RegistryObject<Block> GLOW_SHROOM = REGISTRY.register("glow_shroom", () -> new GlowShroomBlock());
	public static final RegistryObject<Block> WALLNUT = REGISTRY.register("wallnut", () -> new WallnutBlock());
	public static final RegistryObject<Block> MOLTEN_OBSIDIAN = REGISTRY.register("molten_obsidian", () -> new MoltenObsidianBlock());
	public static final RegistryObject<Block> FIREFLY_LANTERN = REGISTRY.register("firefly_lantern", () -> new FireflyLanternBlock());
	public static final RegistryObject<Block> EMPTY_LANTERN = REGISTRY.register("empty_lantern", () -> new EmptyLanternBlock());
	public static final RegistryObject<Block> COARSE_GRASS_BLOCK = REGISTRY.register("coarse_grass_block", () -> new CoarseGrassBlockBlock());
	public static final RegistryObject<Block> PLASTIC_ORE = REGISTRY.register("plastic_ore", () -> new PlasticOreBlock());
	public static final RegistryObject<Block> PLASTIC_BLOCK = REGISTRY.register("plastic_block", () -> new PlasticBlockBlock());
	public static final RegistryObject<Block> CAN_BEANS = REGISTRY.register("can_beans", () -> new CanBeansBlock());
	public static final RegistryObject<Block> CAN_RABBIT_STEW = REGISTRY.register("can_rabbit_stew", () -> new CanRabbitStewBlock());
	public static final RegistryObject<Block> CAN_SUSPICIOUS_STEW = REGISTRY.register("can_suspicious_stew", () -> new CanSuspiciousStewBlock());
	public static final RegistryObject<Block> CAN_BREAD = REGISTRY.register("can_bread", () -> new CanBreadBlock());
	public static final RegistryObject<Block> CAN_MUSHROOM_STEW = REGISTRY.register("can_mushroom_stew", () -> new CanMushroomStewBlock());
	public static final RegistryObject<Block> DEADWOOD_WOOD = REGISTRY.register("deadwood_wood", () -> new DeadwoodWoodBlock());
	public static final RegistryObject<Block> DEADWOOD_LOG = REGISTRY.register("deadwood_log", () -> new DeadwoodLogBlock());
	public static final RegistryObject<Block> DEADWOOD_PLANKS = REGISTRY.register("deadwood_planks", () -> new DeadwoodPlanksBlock());
	public static final RegistryObject<Block> DEADWOOD_LEAVES = REGISTRY.register("deadwood_leaves", () -> new DeadwoodLeavesBlock());
	public static final RegistryObject<Block> DEADWOOD_STAIRS = REGISTRY.register("deadwood_stairs", () -> new DeadwoodStairsBlock());
	public static final RegistryObject<Block> DEADWOOD_SLAB = REGISTRY.register("deadwood_slab", () -> new DeadwoodSlabBlock());
	public static final RegistryObject<Block> DEADWOOD_FENCE = REGISTRY.register("deadwood_fence", () -> new DeadwoodFenceBlock());
	public static final RegistryObject<Block> DEADWOOD_FENCE_GATE = REGISTRY.register("deadwood_fence_gate", () -> new DeadwoodFenceGateBlock());
	public static final RegistryObject<Block> DEADWOOD_PRESSURE_PLATE = REGISTRY.register("deadwood_pressure_plate", () -> new DeadwoodPressurePlateBlock());
	public static final RegistryObject<Block> DEADWOOD_BUTTON = REGISTRY.register("deadwood_button", () -> new DeadwoodButtonBlock());
	public static final RegistryObject<Block> DRIED_LEAVES = REGISTRY.register("dried_leaves", () -> new DriedLeavesBlock());
	public static final RegistryObject<Block> ACID = REGISTRY.register("acid", () -> new AcidBlock());
	public static final RegistryObject<Block> COCONUT_BLOCK = REGISTRY.register("coconut_block", () -> new CoconutBlockBlock());
	public static final RegistryObject<Block> BACKROOM_TRIGGER = REGISTRY.register("backroom_trigger", () -> new BackroomTriggerBlock());
	public static final RegistryObject<Block> CORN_CROP_0 = REGISTRY.register("corn_crop_0", () -> new CornCrop0Block());
	public static final RegistryObject<Block> CORN_CROP_1 = REGISTRY.register("corn_crop_1", () -> new CornCrop1Block());
	public static final RegistryObject<Block> CORN_CROP_2 = REGISTRY.register("corn_crop_2", () -> new CornCrop2Block());
	public static final RegistryObject<Block> TOMATO_BUSH = REGISTRY.register("tomato_bush", () -> new TomatoBushBlock());
	public static final RegistryObject<Block> TOMATO_BUSH_1 = REGISTRY.register("tomato_bush_1", () -> new TomatoBush1Block());
	public static final RegistryObject<Block> TOMATO_BUSH_2 = REGISTRY.register("tomato_bush_2", () -> new TomatoBush2Block());
	public static final RegistryObject<Block> TOMATO_BUSH_3 = REGISTRY.register("tomato_bush_3", () -> new TomatoBush3Block());
	public static final RegistryObject<Block> IRIS_PURPLE = REGISTRY.register("iris_purple", () -> new IrisPurpleBlock());
	public static final RegistryObject<Block> IRIS_SILVER = REGISTRY.register("iris_silver", () -> new IrisSilverBlock());

	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			CoarseGrassBlockBlock.blockColorLoad(event);
		}

		@SubscribeEvent
		public static void itemColorLoad(RegisterColorHandlersEvent.Item event) {
			CoarseGrassBlockBlock.itemColorLoad(event);
		}
	}
}
