
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.kraftmine.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import net.mcreator.kraftmine.item.WoodenCupItem;
import net.mcreator.kraftmine.item.WoodenBatItem;
import net.mcreator.kraftmine.item.WoodIngotItem;
import net.mcreator.kraftmine.item.WoodArmorItem;
import net.mcreator.kraftmine.item.WineGlassItem;
import net.mcreator.kraftmine.item.WeaponSmithVoucherItem;
import net.mcreator.kraftmine.item.WaterGoldItem;
import net.mcreator.kraftmine.item.WaterCupMugItem;
import net.mcreator.kraftmine.item.WaterCupItem;
import net.mcreator.kraftmine.item.WaterCupGlassItem;
import net.mcreator.kraftmine.item.WaterChargeItem;
import net.mcreator.kraftmine.item.WarpStarItem;
import net.mcreator.kraftmine.item.VolumetricShardItem;
import net.mcreator.kraftmine.item.UnoReverseCardItem;
import net.mcreator.kraftmine.item.TungstenSwordItem;
import net.mcreator.kraftmine.item.TungstenShovelItem;
import net.mcreator.kraftmine.item.TungstenPickaxeItem;
import net.mcreator.kraftmine.item.TungstenIngotItem;
import net.mcreator.kraftmine.item.TungstenHoeItem;
import net.mcreator.kraftmine.item.TungstenClaymoreItem;
import net.mcreator.kraftmine.item.TungstenAxeItem;
import net.mcreator.kraftmine.item.TungstenArmorItem;
import net.mcreator.kraftmine.item.TranscendenceShardItem;
import net.mcreator.kraftmine.item.TotemofcreepingItem;
import net.mcreator.kraftmine.item.TotemDyingItem;
import net.mcreator.kraftmine.item.TomeofKnowledgeGunItem;
import net.mcreator.kraftmine.item.TomatoseedsItem;
import net.mcreator.kraftmine.item.TomatoShurikenItem;
import net.mcreator.kraftmine.item.TitaniumIngotItem;
import net.mcreator.kraftmine.item.TitaniumArmorItem;
import net.mcreator.kraftmine.item.TimeShardItem;
import net.mcreator.kraftmine.item.TheSwitcherItem;
import net.mcreator.kraftmine.item.TestDummyItemItem;
import net.mcreator.kraftmine.item.TNTArmorItem;
import net.mcreator.kraftmine.item.StuddedArmorItem;
import net.mcreator.kraftmine.item.StonespearItem;
import net.mcreator.kraftmine.item.StickOfDeathItem;
import net.mcreator.kraftmine.item.SpriteCranberryItem;
import net.mcreator.kraftmine.item.SoulSpriteItem;
import net.mcreator.kraftmine.item.SoulSightItem;
import net.mcreator.kraftmine.item.SoulRightItem;
import net.mcreator.kraftmine.item.SoulNightItem;
import net.mcreator.kraftmine.item.SoulMightItem;
import net.mcreator.kraftmine.item.SoulLightItem;
import net.mcreator.kraftmine.item.SoulFrightItem;
import net.mcreator.kraftmine.item.SoulFlightItem;
import net.mcreator.kraftmine.item.SoulCalciteItem;
import net.mcreator.kraftmine.item.SoulBlightItem;
import net.mcreator.kraftmine.item.SeedMachineGunItem;
import net.mcreator.kraftmine.item.SapphireCoinItem;
import net.mcreator.kraftmine.item.SaphhireItem;
import net.mcreator.kraftmine.item.SandstoneSwordItem;
import net.mcreator.kraftmine.item.SandstoneShovelItem;
import net.mcreator.kraftmine.item.SandstonePickaxeItem;
import net.mcreator.kraftmine.item.SandstoneHoeItem;
import net.mcreator.kraftmine.item.SandstoneAxeItem;
import net.mcreator.kraftmine.item.SaberYellowItem;
import net.mcreator.kraftmine.item.SaberWhiteItem;
import net.mcreator.kraftmine.item.SaberRedItem;
import net.mcreator.kraftmine.item.SaberPurpleItem;
import net.mcreator.kraftmine.item.SaberOrangeItem;
import net.mcreator.kraftmine.item.SaberGreenItem;
import net.mcreator.kraftmine.item.SaberDarkItem;
import net.mcreator.kraftmine.item.RubyItem;
import net.mcreator.kraftmine.item.RubyCoinItem;
import net.mcreator.kraftmine.item.RockPotionItem;
import net.mcreator.kraftmine.item.RoadConeItem;
import net.mcreator.kraftmine.item.RedstoneIngotItem;
import net.mcreator.kraftmine.item.RedstoneArmorItem;
import net.mcreator.kraftmine.item.RealityShardItem;
import net.mcreator.kraftmine.item.ReactorCoreLowItem;
import net.mcreator.kraftmine.item.ReactorCoreItem;
import net.mcreator.kraftmine.item.RangedTomatoItem;
import net.mcreator.kraftmine.item.QuiverItemItem;
import net.mcreator.kraftmine.item.QuiverItem;
import net.mcreator.kraftmine.item.ProbabilitiesShardItem;
import net.mcreator.kraftmine.item.PrismarineSwordItem;
import net.mcreator.kraftmine.item.PrismarineShovelItem;
import net.mcreator.kraftmine.item.PrismarinePickaxeItem;
import net.mcreator.kraftmine.item.PrismarineHoeItem;
import net.mcreator.kraftmine.item.PrismarineAxeItem;
import net.mcreator.kraftmine.item.PrismarineArmorItem;
import net.mcreator.kraftmine.item.PositioningShardItem;
import net.mcreator.kraftmine.item.PopCornItem;
import net.mcreator.kraftmine.item.PlateArmorItem;
import net.mcreator.kraftmine.item.PlasticWaterBottleItem;
import net.mcreator.kraftmine.item.PlasticWaterBottle45Item;
import net.mcreator.kraftmine.item.PlasticWaterBottle35Item;
import net.mcreator.kraftmine.item.PlasticWaterBottle25Item;
import net.mcreator.kraftmine.item.PlasticWaterBottle15Item;
import net.mcreator.kraftmine.item.PlasticSwordItem;
import net.mcreator.kraftmine.item.PlasticShovelItem;
import net.mcreator.kraftmine.item.PlasticScrapItem;
import net.mcreator.kraftmine.item.PlasticPickaxeItem;
import net.mcreator.kraftmine.item.PlasticKatanaItem;
import net.mcreator.kraftmine.item.PlasticItem;
import net.mcreator.kraftmine.item.PlasticHoeItem;
import net.mcreator.kraftmine.item.PlasticGlaiveItem;
import net.mcreator.kraftmine.item.PlasticCutlassItem;
import net.mcreator.kraftmine.item.PlasticClaymoreItem;
import net.mcreator.kraftmine.item.PlasticBroadswordItem;
import net.mcreator.kraftmine.item.PlasticBottleItem;
import net.mcreator.kraftmine.item.PlasticAxeItem;
import net.mcreator.kraftmine.item.PlasticArmorItem;
import net.mcreator.kraftmine.item.PlantChargeItem;
import net.mcreator.kraftmine.item.PhantomPotionItem;
import net.mcreator.kraftmine.item.PebbleItem;
import net.mcreator.kraftmine.item.OmnipotenceShardItem;
import net.mcreator.kraftmine.item.ObsidiantoolsSwordItem;
import net.mcreator.kraftmine.item.ObsidiantoolsShovelItem;
import net.mcreator.kraftmine.item.ObsidiantoolsPickaxeItem;
import net.mcreator.kraftmine.item.ObsidiantoolsHoeItem;
import net.mcreator.kraftmine.item.ObsidiantoolsAxeItem;
import net.mcreator.kraftmine.item.ObsidianscrapItem;
import net.mcreator.kraftmine.item.ObsidianShearsItem;
import net.mcreator.kraftmine.item.ObsidianNuggetItem;
import net.mcreator.kraftmine.item.ObsidianArmorItem;
import net.mcreator.kraftmine.item.NickelIngotItem;
import net.mcreator.kraftmine.item.NickelArmorItem;
import net.mcreator.kraftmine.item.NextbotSpawnEggItem;
import net.mcreator.kraftmine.item.NethersWrathItem;
import net.mcreator.kraftmine.item.NetheriteBattleAxeItem;
import net.mcreator.kraftmine.item.MusicDisc0Item;
import net.mcreator.kraftmine.item.MugItem;
import net.mcreator.kraftmine.item.MeteoriteItem;
import net.mcreator.kraftmine.item.MPPotatoItem;
import net.mcreator.kraftmine.item.LightningRodItem;
import net.mcreator.kraftmine.item.LavaArmorItem;
import net.mcreator.kraftmine.item.LapisLazuliArmorItem;
import net.mcreator.kraftmine.item.IronSpearItem;
import net.mcreator.kraftmine.item.InitialShardItem;
import net.mcreator.kraftmine.item.InfinitePotionWaterBreathingItem;
import net.mcreator.kraftmine.item.InfinitePotionSwiftnessItem;
import net.mcreator.kraftmine.item.InfinitePotionStrengthItem;
import net.mcreator.kraftmine.item.InfinitePotionSlowFallingItem;
import net.mcreator.kraftmine.item.InfinitePotionSaturationItem;
import net.mcreator.kraftmine.item.InfinitePotionRevitalizationItem;
import net.mcreator.kraftmine.item.InfinitePotionResistanceItem;
import net.mcreator.kraftmine.item.InfinitePotionNightVisionItem;
import net.mcreator.kraftmine.item.InfinitePotionLeapingItem;
import net.mcreator.kraftmine.item.InfinitePotionInvisibilityItem;
import net.mcreator.kraftmine.item.InfinitePotionHydrationItem;
import net.mcreator.kraftmine.item.InfinitePotionFireResistanceItem;
import net.mcreator.kraftmine.item.InfinitePotionDripItem;
import net.mcreator.kraftmine.item.IcewandProjectileItem;
import net.mcreator.kraftmine.item.IceWandItem;
import net.mcreator.kraftmine.item.IceSwordItem;
import net.mcreator.kraftmine.item.IceShovelItem;
import net.mcreator.kraftmine.item.IcePickaxeItem;
import net.mcreator.kraftmine.item.IceHoeItem;
import net.mcreator.kraftmine.item.IceAxeItem;
import net.mcreator.kraftmine.item.HydroArmorItem;
import net.mcreator.kraftmine.item.HuskClawItem;
import net.mcreator.kraftmine.item.GolemsArmItem;
import net.mcreator.kraftmine.item.GlassSwordItem;
import net.mcreator.kraftmine.item.GlassShovelItem;
import net.mcreator.kraftmine.item.GlassPickaxeItem;
import net.mcreator.kraftmine.item.GlassHoeItem;
import net.mcreator.kraftmine.item.GlassAxeItem;
import net.mcreator.kraftmine.item.GlaiveBlueprintsItem;
import net.mcreator.kraftmine.item.GigaPotionXItem;
import net.mcreator.kraftmine.item.GigaArmorItem;
import net.mcreator.kraftmine.item.GhillieSuitItem;
import net.mcreator.kraftmine.item.FryingPanItem;
import net.mcreator.kraftmine.item.FoodMaterwelonItem;
import net.mcreator.kraftmine.item.FireScepterItem;
import net.mcreator.kraftmine.item.FireBrandItem;
import net.mcreator.kraftmine.item.EyepatchItem;
import net.mcreator.kraftmine.item.ExcaliburItem;
import net.mcreator.kraftmine.item.EmeraldcoinItem;
import net.mcreator.kraftmine.item.EggshellItem;
import net.mcreator.kraftmine.item.EgghellArmorItem;
import net.mcreator.kraftmine.item.EggArmorItem;
import net.mcreator.kraftmine.item.DrumstickItem;
import net.mcreator.kraftmine.item.DripArmorItem;
import net.mcreator.kraftmine.item.DiscToreadorsItem;
import net.mcreator.kraftmine.item.DiscPvZItem;
import net.mcreator.kraftmine.item.DirtrodItem;
import net.mcreator.kraftmine.item.DiamondsaberItem;
import net.mcreator.kraftmine.item.DiamondCoinItem;
import net.mcreator.kraftmine.item.DepressureHelmetItem;
import net.mcreator.kraftmine.item.DaggerItem;
import net.mcreator.kraftmine.item.CursedIronArmorItem;
import net.mcreator.kraftmine.item.CrystalredItem;
import net.mcreator.kraftmine.item.CrystalYellowItem;
import net.mcreator.kraftmine.item.CrystalWhiteItem;
import net.mcreator.kraftmine.item.CrystalPurpleItem;
import net.mcreator.kraftmine.item.CrystalOrangeItem;
import net.mcreator.kraftmine.item.CrystalGreenItem;
import net.mcreator.kraftmine.item.CrystalDarkItem;
import net.mcreator.kraftmine.item.CrystalBlueItem;
import net.mcreator.kraftmine.item.CornSeedsItem;
import net.mcreator.kraftmine.item.CornItem;
import net.mcreator.kraftmine.item.CookedLeavesItem;
import net.mcreator.kraftmine.item.CookedDrumstickItem;
import net.mcreator.kraftmine.item.CookedCarabeefItem;
import net.mcreator.kraftmine.item.CondensedArmorItem;
import net.mcreator.kraftmine.item.CoconutItem;
import net.mcreator.kraftmine.item.CocaColaGrenadeItem;
import net.mcreator.kraftmine.item.ClayWaterBottleItem;
import net.mcreator.kraftmine.item.ClayWaterBottle23Item;
import net.mcreator.kraftmine.item.ClayWaterBottle13Item;
import net.mcreator.kraftmine.item.ClayMilkBottleItem;
import net.mcreator.kraftmine.item.ClayBottleItem;
import net.mcreator.kraftmine.item.CherryItem;
import net.mcreator.kraftmine.item.ChaliceItem;
import net.mcreator.kraftmine.item.CarbonFiberItem;
import net.mcreator.kraftmine.item.CarbonArmorItem;
import net.mcreator.kraftmine.item.CarabeefItem;
import net.mcreator.kraftmine.item.CanItem;
import net.mcreator.kraftmine.item.CactusArmorItem;
import net.mcreator.kraftmine.item.BlueprintsShortswordItem;
import net.mcreator.kraftmine.item.BlueprintsKatanaItem;
import net.mcreator.kraftmine.item.BlueprintsItem;
import net.mcreator.kraftmine.item.BlueprintsCutlassItem;
import net.mcreator.kraftmine.item.BlueprintsClaymoreItem;
import net.mcreator.kraftmine.item.BlueprintsBroadswordItem;
import net.mcreator.kraftmine.item.BladeRazorItem;
import net.mcreator.kraftmine.item.BladeOfDespairItem;
import net.mcreator.kraftmine.item.BeetzookaItem;
import net.mcreator.kraftmine.item.BeetsniperItem;
import net.mcreator.kraftmine.item.BambooSwordItem;
import net.mcreator.kraftmine.item.BambooShovelItem;
import net.mcreator.kraftmine.item.BambooPickaxeItem;
import net.mcreator.kraftmine.item.BambooHoeItem;
import net.mcreator.kraftmine.item.BambooAxeItem;
import net.mcreator.kraftmine.item.AscendanceShardItem;
import net.mcreator.kraftmine.item.AmogusSpawnEggItem;
import net.mcreator.kraftmine.item.AluminumItem;
import net.mcreator.kraftmine.item.AltitudeShardItem;
import net.mcreator.kraftmine.item.AetherItem;
import net.mcreator.kraftmine.item.AcidItem;
import net.mcreator.kraftmine.KraftmineMod;

public class KraftmineModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, KraftmineMod.MODID);
	public static final RegistryObject<Item> MAHOGANY_WOOD = block(KraftmineModBlocks.MAHOGANY_WOOD, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> MAHOGANY_LOG = block(KraftmineModBlocks.MAHOGANY_LOG, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> MAHOGANY_PLANKS = block(KraftmineModBlocks.MAHOGANY_PLANKS, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> MAHOGANY_LEAVES = block(KraftmineModBlocks.MAHOGANY_LEAVES, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> MAHOGANY_STAIRS = block(KraftmineModBlocks.MAHOGANY_STAIRS, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> MAHOGANY_SLAB = block(KraftmineModBlocks.MAHOGANY_SLAB, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> MAHOGANY_FENCE = block(KraftmineModBlocks.MAHOGANY_FENCE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> MAHOGANY_FENCE_GATE = block(KraftmineModBlocks.MAHOGANY_FENCE_GATE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> MAHOGANY_PRESSURE_PLATE = block(KraftmineModBlocks.MAHOGANY_PRESSURE_PLATE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> MAHOGANY_BUTTON = block(KraftmineModBlocks.MAHOGANY_BUTTON, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CHERRY_WOOD = block(KraftmineModBlocks.CHERRY_WOOD, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CHERRY_LOG = block(KraftmineModBlocks.CHERRY_LOG, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CHERRY_PLANKS = block(KraftmineModBlocks.CHERRY_PLANKS, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CHERRY_LEAVES = block(KraftmineModBlocks.CHERRY_LEAVES, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CHERRY_STAIRS = block(KraftmineModBlocks.CHERRY_STAIRS, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CHERRY_SLAB = block(KraftmineModBlocks.CHERRY_SLAB, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CHERRY_FENCE_GATE = block(KraftmineModBlocks.CHERRY_FENCE_GATE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CHERRY_BUTTON = block(KraftmineModBlocks.CHERRY_BUTTON, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> PALM_WOOD_WOOD = block(KraftmineModBlocks.PALM_WOOD_WOOD, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> PALM_WOOD_LOG = block(KraftmineModBlocks.PALM_WOOD_LOG, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> PALM_WOOD_PLANKS = block(KraftmineModBlocks.PALM_WOOD_PLANKS, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> PALM_WOOD_LEAVES = block(KraftmineModBlocks.PALM_WOOD_LEAVES, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> PALM_WOOD_STAIRS = block(KraftmineModBlocks.PALM_WOOD_STAIRS, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> PALM_WOOD_SLAB = block(KraftmineModBlocks.PALM_WOOD_SLAB, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> PALM_WOOD_FENCE = block(KraftmineModBlocks.PALM_WOOD_FENCE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> PALM_WOOD_PRESSURE_PLATE = block(KraftmineModBlocks.PALM_WOOD_PRESSURE_PLATE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> PALM_WOOD_BUTTON = block(KraftmineModBlocks.PALM_WOOD_BUTTON, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> BAMBOO_PLANKS = block(KraftmineModBlocks.BAMBOO_PLANKS, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> BAMBOO_STAIRS = block(KraftmineModBlocks.BAMBOO_STAIRS, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> BAMBOO_SLAB = block(KraftmineModBlocks.BAMBOO_SLAB, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> BAMBOO_FENCE = block(KraftmineModBlocks.BAMBOO_FENCE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> BAMBOO_FENCE_GATE = block(KraftmineModBlocks.BAMBOO_FENCE_GATE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> BAMBOO_PRESSURE_PLATE = block(KraftmineModBlocks.BAMBOO_PRESSURE_PLATE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> BAMBOO_BUTTON = block(KraftmineModBlocks.BAMBOO_BUTTON, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> TOMATO = REGISTRY.register("tomato", () -> new RangedTomatoItem());
	public static final RegistryObject<Item> APPLEBLOCK = block(KraftmineModBlocks.APPLEBLOCK, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> TUNGSTEN_ORE = block(KraftmineModBlocks.TUNGSTEN_ORE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> TUNGSTEN_BLOCK = block(KraftmineModBlocks.TUNGSTEN_BLOCK, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CLOUD = block(KraftmineModBlocks.CLOUD, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CLOUD_BLOCK_RAIN = block(KraftmineModBlocks.CLOUD_BLOCK_RAIN, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CLOUD_SAPPHIRE_ORE = block(KraftmineModBlocks.CLOUD_SAPPHIRE_ORE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CLOUD_RUBY_ORE = block(KraftmineModBlocks.CLOUD_RUBY_ORE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> AETHERANCIENTDEBRIS = block(KraftmineModBlocks.AETHERANCIENTDEBRIS, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> LEGO_BLOCK = block(KraftmineModBlocks.LEGO_BLOCK, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> PEBBLE = REGISTRY.register("pebble", () -> new PebbleItem());
	public static final RegistryObject<Item> TUNGSTEN_PICKAXE = REGISTRY.register("tungsten_pickaxe", () -> new TungstenPickaxeItem());
	public static final RegistryObject<Item> TUNGSTEN_AXE = REGISTRY.register("tungsten_axe", () -> new TungstenAxeItem());
	public static final RegistryObject<Item> TUNGSTEN_SHOVEL = REGISTRY.register("tungsten_shovel", () -> new TungstenShovelItem());
	public static final RegistryObject<Item> TUNGSTEN_HOE = REGISTRY.register("tungsten_hoe", () -> new TungstenHoeItem());
	public static final RegistryObject<Item> OBSIDIAN_NUGGET = REGISTRY.register("obsidian_nugget", () -> new ObsidianNuggetItem());
	public static final RegistryObject<Item> OBSIDIANSCRAP = REGISTRY.register("obsidianscrap", () -> new ObsidianscrapItem());
	public static final RegistryObject<Item> BAMBOO_PICKAXE = REGISTRY.register("bamboo_pickaxe", () -> new BambooPickaxeItem());
	public static final RegistryObject<Item> BAMBOO_AXE = REGISTRY.register("bamboo_axe", () -> new BambooAxeItem());
	public static final RegistryObject<Item> BAMBOO_SHOVEL = REGISTRY.register("bamboo_shovel", () -> new BambooShovelItem());
	public static final RegistryObject<Item> BAMBOO_HOE = REGISTRY.register("bamboo_hoe", () -> new BambooHoeItem());
	public static final RegistryObject<Item> REACTOR_CORE = REGISTRY.register("reactor_core", () -> new ReactorCoreItem());
	public static final RegistryObject<Item> REACTOR_CORE_LOW = REGISTRY.register("reactor_core_low", () -> new ReactorCoreLowItem());
	public static final RegistryObject<Item> CRYSTALRED = REGISTRY.register("crystalred", () -> new CrystalredItem());
	public static final RegistryObject<Item> CRYSTAL_GREEN = REGISTRY.register("crystal_green", () -> new CrystalGreenItem());
	public static final RegistryObject<Item> CRYSTAL_PURPLE = REGISTRY.register("crystal_purple", () -> new CrystalPurpleItem());
	public static final RegistryObject<Item> CRYSTAL_YELLOW = REGISTRY.register("crystal_yellow", () -> new CrystalYellowItem());
	public static final RegistryObject<Item> CRYSTAL_ORANGE = REGISTRY.register("crystal_orange", () -> new CrystalOrangeItem());
	public static final RegistryObject<Item> CRYSTAL_BLUE = REGISTRY.register("crystal_blue", () -> new CrystalBlueItem());
	public static final RegistryObject<Item> CRYSTAL_WHITE = REGISTRY.register("crystal_white", () -> new CrystalWhiteItem());
	public static final RegistryObject<Item> CRYSTAL_DARK = REGISTRY.register("crystal_dark", () -> new CrystalDarkItem());
	public static final RegistryObject<Item> TUNGSTEN_INGOT = REGISTRY.register("tungsten_ingot", () -> new TungstenIngotItem());
	public static final RegistryObject<Item> CHERRY_FENCE = block(KraftmineModBlocks.CHERRY_FENCE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CHERRY_PRESSURE_PLATE = block(KraftmineModBlocks.CHERRY_PRESSURE_PLATE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> PALM_WOOD_FENCE_GATE = block(KraftmineModBlocks.PALM_WOOD_FENCE_GATE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> WOODEN_CUP = REGISTRY.register("wooden_cup", () -> new WoodenCupItem());
	public static final RegistryObject<Item> WINE_GLASS = REGISTRY.register("wine_glass", () -> new WineGlassItem());
	public static final RegistryObject<Item> MUG = REGISTRY.register("mug", () -> new MugItem());
	public static final RegistryObject<Item> CHALICE = REGISTRY.register("chalice", () -> new ChaliceItem());
	public static final RegistryObject<Item> FOOD_MATERWELON = REGISTRY.register("food_materwelon", () -> new FoodMaterwelonItem());
	public static final RegistryObject<Item> CHERRY = REGISTRY.register("cherry", () -> new CherryItem());
	public static final RegistryObject<Item> CORN = REGISTRY.register("corn", () -> new CornItem());
	public static final RegistryObject<Item> CORN_SEEDS = REGISTRY.register("corn_seeds", () -> new CornSeedsItem());
	public static final RegistryObject<Item> WATER_CUP = REGISTRY.register("water_cup", () -> new WaterCupItem());
	public static final RegistryObject<Item> WATER_CUP_GLASS = REGISTRY.register("water_cup_glass", () -> new WaterCupGlassItem());
	public static final RegistryObject<Item> WATER_CUP_MUG = REGISTRY.register("water_cup_mug", () -> new WaterCupMugItem());
	public static final RegistryObject<Item> WATER_GOLD = REGISTRY.register("water_gold", () -> new WaterGoldItem());
	public static final RegistryObject<Item> WARP_STAR = REGISTRY.register("warp_star", () -> new WarpStarItem());
	public static final RegistryObject<Item> DIRTROD = REGISTRY.register("dirtrod", () -> new DirtrodItem());
	public static final RegistryObject<Item> NICKEL_INGOT = REGISTRY.register("nickel_ingot", () -> new NickelIngotItem());
	public static final RegistryObject<Item> NICKEL_ORE = block(KraftmineModBlocks.NICKEL_ORE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> NICKEL_BLOCK = block(KraftmineModBlocks.NICKEL_BLOCK, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> ALUMINUM = REGISTRY.register("aluminum", () -> new AluminumItem());
	public static final RegistryObject<Item> ALUMINUM_ORE = block(KraftmineModBlocks.ALUMINUM_ORE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> ALUMINUM_BLOCK = block(KraftmineModBlocks.ALUMINUM_BLOCK, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> DEEPSLATE_TUNGSTEN_ORE = block(KraftmineModBlocks.DEEPSLATE_TUNGSTEN_ORE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> TITANIUM_INGOT = REGISTRY.register("titanium_ingot", () -> new TitaniumIngotItem());
	public static final RegistryObject<Item> TITANIUM_ORE = block(KraftmineModBlocks.TITANIUM_ORE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> TITANIUM_BLOCK = block(KraftmineModBlocks.TITANIUM_BLOCK, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> DEEPSLATE_TITANIUM_ORE = block(KraftmineModBlocks.DEEPSLATE_TITANIUM_ORE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CARBON_FIBER = REGISTRY.register("carbon_fiber", () -> new CarbonFiberItem());
	public static final RegistryObject<Item> OBSIDIAN_PICKAXE = REGISTRY.register("obsidian_pickaxe", () -> new ObsidiantoolsPickaxeItem());
	public static final RegistryObject<Item> OBSIDIAN_AXE = REGISTRY.register("obsidian_axe", () -> new ObsidiantoolsAxeItem());
	public static final RegistryObject<Item> OBSIDIAN_SHOVEL = REGISTRY.register("obsidian_shovel", () -> new ObsidiantoolsShovelItem());
	public static final RegistryObject<Item> OBSIDIAN_HOE = REGISTRY.register("obsidian_hoe", () -> new ObsidiantoolsHoeItem());
	public static final RegistryObject<Item> OBSIDIAN_SHEARS = REGISTRY.register("obsidian_shears", () -> new ObsidianShearsItem());
	public static final RegistryObject<Item> REDSTONE_INGOT = REGISTRY.register("redstone_ingot", () -> new RedstoneIngotItem());
	public static final RegistryObject<Item> RUBY = REGISTRY.register("ruby", () -> new RubyItem());
	public static final RegistryObject<Item> RUBY_ORE = block(KraftmineModBlocks.RUBY_ORE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> RUBY_BLOCK = block(KraftmineModBlocks.RUBY_BLOCK, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> SAPHHIRE = REGISTRY.register("saphhire", () -> new SaphhireItem());
	public static final RegistryObject<Item> SAPHHIRE_ORE = block(KraftmineModBlocks.SAPHHIRE_ORE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> SAPHHIRE_BLOCK = block(KraftmineModBlocks.SAPHHIRE_BLOCK, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> INFINITE_POTION_REVITALIZATION = REGISTRY.register("infinite_potion_revitalization", () -> new InfinitePotionRevitalizationItem());
	public static final RegistryObject<Item> INFINITE_POTION_LEAPING = REGISTRY.register("infinite_potion_leaping", () -> new InfinitePotionLeapingItem());
	public static final RegistryObject<Item> INFINITE_POTION_STRENGTH = REGISTRY.register("infinite_potion_strength", () -> new InfinitePotionStrengthItem());
	public static final RegistryObject<Item> INFINITE_POTION_RESISTANCE = REGISTRY.register("infinite_potion_resistance", () -> new InfinitePotionResistanceItem());
	public static final RegistryObject<Item> INFINITE_POTION_FIRE_RESISTANCE = REGISTRY.register("infinite_potion_fire_resistance", () -> new InfinitePotionFireResistanceItem());
	public static final RegistryObject<Item> INFINITE_POTION_INVISIBILITY = REGISTRY.register("infinite_potion_invisibility", () -> new InfinitePotionInvisibilityItem());
	public static final RegistryObject<Item> INFINITE_POTION_SLOW_FALLING = REGISTRY.register("infinite_potion_slow_falling", () -> new InfinitePotionSlowFallingItem());
	public static final RegistryObject<Item> INFINITE_POTION_DRIP = REGISTRY.register("infinite_potion_drip", () -> new InfinitePotionDripItem());
	public static final RegistryObject<Item> INFINITE_POTION_HYDRATION = REGISTRY.register("infinite_potion_hydration", () -> new InfinitePotionHydrationItem());
	public static final RegistryObject<Item> INFINITE_POTION_SATURATION = REGISTRY.register("infinite_potion_saturation", () -> new InfinitePotionSaturationItem());
	public static final RegistryObject<Item> INFINITE_POTION_SWIFTNESS = REGISTRY.register("infinite_potion_swiftness", () -> new InfinitePotionSwiftnessItem());
	public static final RegistryObject<Item> INFINITE_POTION_NIGHT_VISION = REGISTRY.register("infinite_potion_night_vision", () -> new InfinitePotionNightVisionItem());
	public static final RegistryObject<Item> INFINITE_POTION_WATER_BREATHING = REGISTRY.register("infinite_potion_water_breathing", () -> new InfinitePotionWaterBreathingItem());
	public static final RegistryObject<Item> SHARD_POSITIONING = REGISTRY.register("shard_positioning", () -> new PositioningShardItem());
	public static final RegistryObject<Item> SHARD_ALTITUDE = REGISTRY.register("shard_altitude", () -> new AltitudeShardItem());
	public static final RegistryObject<Item> SHARD_VOLUMETRIC = REGISTRY.register("shard_volumetric", () -> new VolumetricShardItem());
	public static final RegistryObject<Item> SHARD_TIME = REGISTRY.register("shard_time", () -> new TimeShardItem());
	public static final RegistryObject<Item> SHARD_POSSIBILITIES = REGISTRY.register("shard_possibilities", () -> new ProbabilitiesShardItem());
	public static final RegistryObject<Item> REALITY_SHARD = REGISTRY.register("reality_shard", () -> new RealityShardItem());
	public static final RegistryObject<Item> INITIAL_SHARD = REGISTRY.register("initial_shard", () -> new InitialShardItem());
	public static final RegistryObject<Item> TRANSCENDENCE_SHARD = REGISTRY.register("transcendence_shard", () -> new TranscendenceShardItem());
	public static final RegistryObject<Item> ASCENDANCE_SHARD = REGISTRY.register("ascendance_shard", () -> new AscendanceShardItem());
	public static final RegistryObject<Item> OMNIPOTENCE_SHARD = REGISTRY.register("omnipotence_shard", () -> new OmnipotenceShardItem());
	public static final RegistryObject<Item> WALL_BLOCK = block(KraftmineModBlocks.WALL_BLOCK, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> MUSIC_DISC_0 = REGISTRY.register("music_disc_0", () -> new MusicDisc0Item());
	public static final RegistryObject<Item> PLANT_CHARGE = REGISTRY.register("plant_charge", () -> new PlantChargeItem());
	public static final RegistryObject<Item> GRAVITY_DISRUPTOR = block(KraftmineModBlocks.GRAVITY_DISRUPTOR, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> GOLDEN_APPLE_BLOCK = block(KraftmineModBlocks.GOLDEN_APPLE_BLOCK, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> BUFFALO_SPAWN_EGG = REGISTRY.register("buffalo_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.BUFFALO, -10066330, -6724096, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> SHROO_MOO_SPAWN_EGG = REGISTRY.register("shroo_moo_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.SHROO_MOO, -1, -10066330, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> PENGUIN_SPAWN_EGG = REGISTRY.register("penguin_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.PENGUIN, -1, -16777165, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> MOB_BIG_SPAWN_EGG = REGISTRY.register("mob_big_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.MOB_BIG, -52225, -256, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> GOOSE_SPAWN_EGG = REGISTRY.register("goose_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.GOOSE, -9421005, -1, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> PARAS_SPAWN_EGG = REGISTRY.register("paras_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.PARAS, -3394816, -3342490, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> ZOMBIE_PIG_MAN_SPAWN_EGG = REGISTRY.register("zombie_pig_man_spawn_egg",
			() -> new ForgeSpawnEggItem(KraftmineModEntities.ZOMBIE_PIG_MAN, -3407668, -16751104, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> FROZEN_ZOMBIE_SPAWN_EGG = REGISTRY.register("frozen_zombie_spawn_egg",
			() -> new ForgeSpawnEggItem(KraftmineModEntities.FROZEN_ZOMBIE, -16751053, -16751002, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> ICEOLOGER_SPAWN_EGG = REGISTRY.register("iceologer_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.ICEOLOGER, -9290715, -13011823, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> GHOST_SPIDER_SPAWN_EGG = REGISTRY.register("ghost_spider_spawn_egg",
			() -> new ForgeSpawnEggItem(KraftmineModEntities.GHOST_SPIDER, -7763575, -5776683, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> MIMIC_ENTITY_SPAWN_EGG = REGISTRY.register("mimic_entity_spawn_egg",
			() -> new ForgeSpawnEggItem(KraftmineModEntities.MIMIC_ENTITY, -3381760, -10066330, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> AMOGUS_SPAWN_EGG = REGISTRY.register("amogus_spawn_egg", () -> new AmogusSpawnEggItem());
	public static final RegistryObject<Item> SIRENHEAD_SPAWN_EGG = REGISTRY.register("sirenhead_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.SIRENHEAD, -12384248, -12970217, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> GIANT_AI_SPAWN_EGG = REGISTRY.register("giant_ai_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.GIANT_AI, -16738048, -10092544, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> MOB_SHADE_SPAWN_EGG = REGISTRY.register("mob_shade_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.MOB_SHADE, -16764058, -16737946, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> SLEUTH_SPAWN_EGG = REGISTRY.register("sleuth_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.SLEUTH, -13421773, -1, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> ANOMALY_SPAWN_EGG = REGISTRY.register("anomaly_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.ANOMALY, -16777216, -10079488, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> MOB_FLOATING_EYE_SPAWN_EGG = REGISTRY.register("mob_floating_eye_spawn_egg",
			() -> new ForgeSpawnEggItem(KraftmineModEntities.MOB_FLOATING_EYE, -1, -3407770, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> NOOB_SPAWN_EGG = REGISTRY.register("noob_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.NOOB, -256, -16737793, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> MICKEY_SPAWN_EGG = REGISTRY.register("mickey_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.MICKEY, -16777216, -65536, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> GENERAL_SPAWN_EGG = REGISTRY.register("general_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.GENERAL, -6724096, -16777216, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> TROLL_SPAWN_EGG = REGISTRY.register("troll_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.TROLL, -1, -16777216, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> TROLLGE_LVL_2_SPAWN_EGG = REGISTRY.register("trollge_lvl_2_spawn_egg",
			() -> new ForgeSpawnEggItem(KraftmineModEntities.TROLLGE_LVL_2, -10066330, -6710887, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> TROLLGE_LVL_3_SPAWN_EGG = REGISTRY.register("trollge_lvl_3_spawn_egg",
			() -> new ForgeSpawnEggItem(KraftmineModEntities.TROLLGE_LVL_3, -16777216, -10066330, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> NOOTNOOT_SPAWN_EGG = REGISTRY.register("nootnoot_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.NOOTNOOT, -16771512, -6160384, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> NEXTBOT_SPAWN_EGG = REGISTRY.register("nextbot_spawn_egg", () -> new NextbotSpawnEggItem());
	public static final RegistryObject<Item> AETHER = REGISTRY.register("aether", () -> new AetherItem());
	public static final RegistryObject<Item> LIFE_ORB = block(KraftmineModBlocks.LIFE_ORB, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> XP_BANK = block(KraftmineModBlocks.XP_BANK, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> COCONUT = REGISTRY.register("coconut", () -> new CoconutItem());
	public static final RegistryObject<Item> TEST_DUMMY_ITEM = REGISTRY.register("test_dummy_item", () -> new TestDummyItemItem());
	public static final RegistryObject<Item> UNO_REVERSE_CARD = REGISTRY.register("uno_reverse_card", () -> new UnoReverseCardItem());
	public static final RegistryObject<Item> LUCKY_BLOCK = block(KraftmineModBlocks.LUCKY_BLOCK, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> BACKROOM_TRIGGERED_2 = block(KraftmineModBlocks.BACKROOM_TRIGGERED_2, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> DOMAIN_BARRIER = block(KraftmineModBlocks.DOMAIN_BARRIER, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CLAY_BOTTLE = REGISTRY.register("clay_bottle", () -> new ClayBottleItem());
	public static final RegistryObject<Item> CHILL_ICE = block(KraftmineModBlocks.CHILL_ICE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> SUPPLY_CRATE = block(KraftmineModBlocks.SUPPLY_CRATE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> PHANTOM_POTION = REGISTRY.register("phantom_potion", () -> new PhantomPotionItem());
	public static final RegistryObject<Item> ROCK_POTION = REGISTRY.register("rock_potion", () -> new RockPotionItem());
	public static final RegistryObject<Item> GLOW_SHROOM = block(KraftmineModBlocks.GLOW_SHROOM, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> TOMATOSEEDS = REGISTRY.register("tomatoseeds", () -> new TomatoseedsItem());
	public static final RegistryObject<Item> CARABEEF = REGISTRY.register("carabeef", () -> new CarabeefItem());
	public static final RegistryObject<Item> COOKED_CARABEEF = REGISTRY.register("cooked_carabeef", () -> new CookedCarabeefItem());
	public static final RegistryObject<Item> WALLNUT = block(KraftmineModBlocks.WALLNUT, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> TOTEMOFCREEPING = REGISTRY.register("totemofcreeping", () -> new TotemofcreepingItem());
	public static final RegistryObject<Item> SOUL_FLIGHT = REGISTRY.register("soul_flight", () -> new SoulFlightItem());
	public static final RegistryObject<Item> SOUL_FRIGHT = REGISTRY.register("soul_fright", () -> new SoulFrightItem());
	public static final RegistryObject<Item> SOUL_SIGHT = REGISTRY.register("soul_sight", () -> new SoulSightItem());
	public static final RegistryObject<Item> SOUL_MIGHT = REGISTRY.register("soul_might", () -> new SoulMightItem());
	public static final RegistryObject<Item> SOUL_NIGHT = REGISTRY.register("soul_night", () -> new SoulNightItem());
	public static final RegistryObject<Item> SOUL_LIGHT = REGISTRY.register("soul_light", () -> new SoulLightItem());
	public static final RegistryObject<Item> SOUL_BLIGHT = REGISTRY.register("soul_blight", () -> new SoulBlightItem());
	public static final RegistryObject<Item> SOUL_CALCITE = REGISTRY.register("soul_calcite", () -> new SoulCalciteItem());
	public static final RegistryObject<Item> SOUL_SPRITE = REGISTRY.register("soul_sprite", () -> new SoulSpriteItem());
	public static final RegistryObject<Item> SOUL_RIGHT = REGISTRY.register("soul_right", () -> new SoulRightItem());
	public static final RegistryObject<Item> EGGSHELL = REGISTRY.register("eggshell", () -> new EggshellItem());
	public static final RegistryObject<Item> MOLTEN_OBSIDIAN = block(KraftmineModBlocks.MOLTEN_OBSIDIAN, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> FIREFLY_LANTERN = block(KraftmineModBlocks.FIREFLY_LANTERN, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> EMPTY_LANTERN = block(KraftmineModBlocks.EMPTY_LANTERN, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> GHOST_SPIDER_MUTANT_SPAWN_EGG = REGISTRY.register("ghost_spider_mutant_spawn_egg",
			() -> new ForgeSpawnEggItem(KraftmineModEntities.GHOST_SPIDER_MUTANT, -10066330, -10092544, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> WOOD_INGOT = REGISTRY.register("wood_ingot", () -> new WoodIngotItem());
	public static final RegistryObject<Item> COOKED_LEAVES = REGISTRY.register("cooked_leaves", () -> new CookedLeavesItem());
	public static final RegistryObject<Item> COARSE_GRASS_BLOCK = block(KraftmineModBlocks.COARSE_GRASS_BLOCK, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CAN = REGISTRY.register("can", () -> new CanItem());
	public static final RegistryObject<Item> SPRITE_CRANBERRY = REGISTRY.register("sprite_cranberry", () -> new SpriteCranberryItem());
	public static final RegistryObject<Item> PLASTIC = REGISTRY.register("plastic", () -> new PlasticItem());
	public static final RegistryObject<Item> PLASTIC_ORE = block(KraftmineModBlocks.PLASTIC_ORE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> PLASTIC_BLOCK = block(KraftmineModBlocks.PLASTIC_BLOCK, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> PLASTIC_PICKAXE = REGISTRY.register("plastic_pickaxe", () -> new PlasticPickaxeItem());
	public static final RegistryObject<Item> PLASTIC_AXE = REGISTRY.register("plastic_axe", () -> new PlasticAxeItem());
	public static final RegistryObject<Item> PLASTIC_SHOVEL = REGISTRY.register("plastic_shovel", () -> new PlasticShovelItem());
	public static final RegistryObject<Item> PLASTIC_HOE = REGISTRY.register("plastic_hoe", () -> new PlasticHoeItem());
	public static final RegistryObject<Item> WASP_SPAWN_EGG = REGISTRY.register("wasp_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.WASP, -16777216, -256, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> STICK_HORSE_SPAWN_EGG = REGISTRY.register("stick_horse_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.STICK_HORSE, -6584243, -3158103, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> CAN_BEANS = block(KraftmineModBlocks.CAN_BEANS, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CAN_RABBIT_STEW = block(KraftmineModBlocks.CAN_RABBIT_STEW, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CAN_SUSPICIOUS_STEW = block(KraftmineModBlocks.CAN_SUSPICIOUS_STEW, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CAN_BREAD = block(KraftmineModBlocks.CAN_BREAD, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> CAN_MUSHROOM_STEW = block(KraftmineModBlocks.CAN_MUSHROOM_STEW, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> GIANT_SQUID_SPAWN_EGG = REGISTRY.register("giant_squid_spawn_egg",
			() -> new ForgeSpawnEggItem(KraftmineModEntities.GIANT_SQUID, -16750951, -3381760, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> CATFISH_SPAWN_EGG = REGISTRY.register("catfish_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.CATFISH, -26266, -16750849, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> SKELETURTLE_SPAWN_EGG = REGISTRY.register("skeleturtle_spawn_egg",
			() -> new ForgeSpawnEggItem(KraftmineModEntities.SKELETURTLE, -10837599, -9408400, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> AMONGAMITE_SPAWN_EGG = REGISTRY.register("amongamite_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.AMONGAMITE, -10066330, -3407872, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> IRON_DROID_SPAWN_EGG = REGISTRY.register("iron_droid_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.IRON_DROID, -1, -6724096, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> PLAGUE_WITCH_SPAWN_EGG = REGISTRY.register("plague_witch_spawn_egg",
			() -> new ForgeSpawnEggItem(KraftmineModEntities.PLAGUE_WITCH, -10092442, -10066330, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> CREEPIEST_SPAWN_EGG = REGISTRY.register("creepiest_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.CREEPIEST, -16751104, -16738048, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> DUCK_SPAWN_EGG = REGISTRY.register("duck_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.DUCK, -16738048, -10079488, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> CREEP_SPAWN_EGG = REGISTRY.register("creep_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.CREEP, -16751104, -16777216, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> CHOMPER_SPAWN_EGG = REGISTRY.register("chomper_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.CHOMPER, -16751104, -6750106, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> EMERALDCOIN = REGISTRY.register("emeraldcoin", () -> new EmeraldcoinItem());
	public static final RegistryObject<Item> PLASTIC_SCRAP = REGISTRY.register("plastic_scrap", () -> new PlasticScrapItem());
	public static final RegistryObject<Item> SAPPHIRE_COIN = REGISTRY.register("sapphire_coin", () -> new SapphireCoinItem());
	public static final RegistryObject<Item> RUBY_COIN = REGISTRY.register("ruby_coin", () -> new RubyCoinItem());
	public static final RegistryObject<Item> DIAMOND_COIN = REGISTRY.register("diamond_coin", () -> new DiamondCoinItem());
	public static final RegistryObject<Item> DEADWOOD_WOOD = block(KraftmineModBlocks.DEADWOOD_WOOD, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> DEADWOOD_LOG = block(KraftmineModBlocks.DEADWOOD_LOG, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> DEADWOOD_PLANKS = block(KraftmineModBlocks.DEADWOOD_PLANKS, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> DEADWOOD_LEAVES = block(KraftmineModBlocks.DEADWOOD_LEAVES, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> DEADWOOD_STAIRS = block(KraftmineModBlocks.DEADWOOD_STAIRS, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> DEADWOOD_SLAB = block(KraftmineModBlocks.DEADWOOD_SLAB, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> DEADWOOD_FENCE = block(KraftmineModBlocks.DEADWOOD_FENCE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> DEADWOOD_FENCE_GATE = block(KraftmineModBlocks.DEADWOOD_FENCE_GATE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> DEADWOOD_PRESSURE_PLATE = block(KraftmineModBlocks.DEADWOOD_PRESSURE_PLATE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> DEADWOOD_BUTTON = block(KraftmineModBlocks.DEADWOOD_BUTTON, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> ICE_PICKAXE = REGISTRY.register("ice_pickaxe", () -> new IcePickaxeItem());
	public static final RegistryObject<Item> ICE_AXE = REGISTRY.register("ice_axe", () -> new IceAxeItem());
	public static final RegistryObject<Item> ICE_SHOVEL = REGISTRY.register("ice_shovel", () -> new IceShovelItem());
	public static final RegistryObject<Item> ICE_HOE = REGISTRY.register("ice_hoe", () -> new IceHoeItem());
	public static final RegistryObject<Item> SANDSTONE_PICKAXE = REGISTRY.register("sandstone_pickaxe", () -> new SandstonePickaxeItem());
	public static final RegistryObject<Item> SANDSTONE_AXE = REGISTRY.register("sandstone_axe", () -> new SandstoneAxeItem());
	public static final RegistryObject<Item> SANDSTONE_SHOVEL = REGISTRY.register("sandstone_shovel", () -> new SandstoneShovelItem());
	public static final RegistryObject<Item> SANDSTONE_HOE = REGISTRY.register("sandstone_hoe", () -> new SandstoneHoeItem());
	public static final RegistryObject<Item> PRISMARINE_PICKAXE = REGISTRY.register("prismarine_pickaxe", () -> new PrismarinePickaxeItem());
	public static final RegistryObject<Item> PRISMARINE_AXE = REGISTRY.register("prismarine_axe", () -> new PrismarineAxeItem());
	public static final RegistryObject<Item> PRISMARINE_SWORD = REGISTRY.register("prismarine_sword", () -> new PrismarineSwordItem());
	public static final RegistryObject<Item> PRISMARINE_SHOVEL = REGISTRY.register("prismarine_shovel", () -> new PrismarineShovelItem());
	public static final RegistryObject<Item> PRISMARINE_HOE = REGISTRY.register("prismarine_hoe", () -> new PrismarineHoeItem());
	public static final RegistryObject<Item> GLASS_PICKAXE = REGISTRY.register("glass_pickaxe", () -> new GlassPickaxeItem());
	public static final RegistryObject<Item> GLASS_AXE = REGISTRY.register("glass_axe", () -> new GlassAxeItem());
	public static final RegistryObject<Item> GLASS_SHOVEL = REGISTRY.register("glass_shovel", () -> new GlassShovelItem());
	public static final RegistryObject<Item> GLASS_HOE = REGISTRY.register("glass_hoe", () -> new GlassHoeItem());
	public static final RegistryObject<Item> WATER_CHARGE = REGISTRY.register("water_charge", () -> new WaterChargeItem());
	public static final RegistryObject<Item> STICK_OF_DEATH = REGISTRY.register("stick_of_death", () -> new StickOfDeathItem());
	public static final RegistryObject<Item> TOMEOF_KNOWLEDGE_GUN = REGISTRY.register("tomeof_knowledge_gun", () -> new TomeofKnowledgeGunItem());
	public static final RegistryObject<Item> BLUEPRINTS_GLAIVE = REGISTRY.register("blueprints_glaive", () -> new GlaiveBlueprintsItem());
	public static final RegistryObject<Item> BLUEPRINTS_CUTLASS = REGISTRY.register("blueprints_cutlass", () -> new BlueprintsCutlassItem());
	public static final RegistryObject<Item> BLUEPRINTS_KATANA = REGISTRY.register("blueprints_katana", () -> new BlueprintsKatanaItem());
	public static final RegistryObject<Item> BLUEPRINTS_BROADSWORD = REGISTRY.register("blueprints_broadsword", () -> new BlueprintsBroadswordItem());
	public static final RegistryObject<Item> BLUEPRINTS_SHORTSWORD = REGISTRY.register("blueprints_shortsword", () -> new BlueprintsShortswordItem());
	public static final RegistryObject<Item> BLUEPRINTS_CLAYMORE = REGISTRY.register("blueprints_claymore", () -> new BlueprintsClaymoreItem());
	public static final RegistryObject<Item> BLUEPRINTS = REGISTRY.register("blueprints", () -> new BlueprintsItem());
	public static final RegistryObject<Item> DRIED_LEAVES = block(KraftmineModBlocks.DRIED_LEAVES, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> TOMATO_SHURIKEN = REGISTRY.register("tomato_shuriken", () -> new TomatoShurikenItem());
	public static final RegistryObject<Item> WEAPON_SMITH_VOUCHER = REGISTRY.register("weapon_smith_voucher", () -> new WeaponSmithVoucherItem());
	public static final RegistryObject<Item> DISC_TOREADORS = REGISTRY.register("disc_toreadors", () -> new DiscToreadorsItem());
	public static final RegistryObject<Item> DISC_PV_Z = REGISTRY.register("disc_pv_z", () -> new DiscPvZItem());
	public static final RegistryObject<Item> ACID_BUCKET = REGISTRY.register("acid_bucket", () -> new AcidItem());
	public static final RegistryObject<Item> HUSK_CLAW = REGISTRY.register("husk_claw", () -> new HuskClawItem());
	public static final RegistryObject<Item> GOLEMS_ARM = REGISTRY.register("golems_arm", () -> new GolemsArmItem());
	public static final RegistryObject<Item> FRYING_PAN = REGISTRY.register("frying_pan", () -> new FryingPanItem());
	public static final RegistryObject<Item> STONESPEAR = REGISTRY.register("stonespear", () -> new StonespearItem());
	public static final RegistryObject<Item> BAMBOO_SWORD = REGISTRY.register("bamboo_sword", () -> new BambooSwordItem());
	public static final RegistryObject<Item> OBSIDIAN_SWORD = REGISTRY.register("obsidian_sword", () -> new ObsidiantoolsSwordItem());
	public static final RegistryObject<Item> TUNGSTEN_SWORD = REGISTRY.register("tungsten_sword", () -> new TungstenSwordItem());
	public static final RegistryObject<Item> TUNGSTEN_CLAYMORE = REGISTRY.register("tungsten_claymore", () -> new TungstenClaymoreItem());
	public static final RegistryObject<Item> NETHERS_WRATH = REGISTRY.register("nethers_wrath", () -> new NethersWrathItem());
	public static final RegistryObject<Item> NETHERITE_BATTLE_AXE = REGISTRY.register("netherite_battle_axe", () -> new NetheriteBattleAxeItem());
	public static final RegistryObject<Item> FIRE_BRAND = REGISTRY.register("fire_brand", () -> new FireBrandItem());
	public static final RegistryObject<Item> BLADE_RAZOR = REGISTRY.register("blade_razor", () -> new BladeRazorItem());
	public static final RegistryObject<Item> BLADE_OF_DESPAIR = REGISTRY.register("blade_of_despair", () -> new BladeOfDespairItem());
	public static final RegistryObject<Item> COCA_COLA_GRENADE = REGISTRY.register("coca_cola_grenade", () -> new CocaColaGrenadeItem());
	public static final RegistryObject<Item> SEED_MACHINE_GUN = REGISTRY.register("seed_machine_gun", () -> new SeedMachineGunItem());
	public static final RegistryObject<Item> POP_CORN = REGISTRY.register("pop_corn", () -> new PopCornItem());
	public static final RegistryObject<Item> EYEPATCH_HELMET = REGISTRY.register("eyepatch_helmet", () -> new EyepatchItem.Helmet());
	public static final RegistryObject<Item> DEPRESSURE_HELMET_HELMET = REGISTRY.register("depressure_helmet_helmet", () -> new DepressureHelmetItem.Helmet());
	public static final RegistryObject<Item> ROAD_CONE_HELMET = REGISTRY.register("road_cone_helmet", () -> new RoadConeItem.Helmet());
	public static final RegistryObject<Item> WOOD_ARMOR_HELMET = REGISTRY.register("wood_armor_helmet", () -> new WoodArmorItem.Helmet());
	public static final RegistryObject<Item> WOOD_ARMOR_CHESTPLATE = REGISTRY.register("wood_armor_chestplate", () -> new WoodArmorItem.Chestplate());
	public static final RegistryObject<Item> WOOD_ARMOR_LEGGINGS = REGISTRY.register("wood_armor_leggings", () -> new WoodArmorItem.Leggings());
	public static final RegistryObject<Item> WOOD_ARMOR_BOOTS = REGISTRY.register("wood_armor_boots", () -> new WoodArmorItem.Boots());
	public static final RegistryObject<Item> EGG_ARMOR_HELMET = REGISTRY.register("egg_armor_helmet", () -> new EggArmorItem.Helmet());
	public static final RegistryObject<Item> EGG_ARMOR_CHESTPLATE = REGISTRY.register("egg_armor_chestplate", () -> new EggArmorItem.Chestplate());
	public static final RegistryObject<Item> EGG_ARMOR_LEGGINGS = REGISTRY.register("egg_armor_leggings", () -> new EggArmorItem.Leggings());
	public static final RegistryObject<Item> EGG_ARMOR_BOOTS = REGISTRY.register("egg_armor_boots", () -> new EggArmorItem.Boots());
	public static final RegistryObject<Item> DRIP_ARMOR_HELMET = REGISTRY.register("drip_armor_helmet", () -> new DripArmorItem.Helmet());
	public static final RegistryObject<Item> DRIP_ARMOR_CHESTPLATE = REGISTRY.register("drip_armor_chestplate", () -> new DripArmorItem.Chestplate());
	public static final RegistryObject<Item> DRIP_ARMOR_LEGGINGS = REGISTRY.register("drip_armor_leggings", () -> new DripArmorItem.Leggings());
	public static final RegistryObject<Item> DRIP_ARMOR_BOOTS = REGISTRY.register("drip_armor_boots", () -> new DripArmorItem.Boots());
	public static final RegistryObject<Item> STUDDED_ARMOR_HELMET = REGISTRY.register("studded_armor_helmet", () -> new StuddedArmorItem.Helmet());
	public static final RegistryObject<Item> STUDDED_ARMOR_CHESTPLATE = REGISTRY.register("studded_armor_chestplate", () -> new StuddedArmorItem.Chestplate());
	public static final RegistryObject<Item> STUDDED_ARMOR_LEGGINGS = REGISTRY.register("studded_armor_leggings", () -> new StuddedArmorItem.Leggings());
	public static final RegistryObject<Item> STUDDED_ARMOR_BOOTS = REGISTRY.register("studded_armor_boots", () -> new StuddedArmorItem.Boots());
	public static final RegistryObject<Item> CACTUS_ARMOR_HELMET = REGISTRY.register("cactus_armor_helmet", () -> new CactusArmorItem.Helmet());
	public static final RegistryObject<Item> CACTUS_ARMOR_CHESTPLATE = REGISTRY.register("cactus_armor_chestplate", () -> new CactusArmorItem.Chestplate());
	public static final RegistryObject<Item> CACTUS_ARMOR_LEGGINGS = REGISTRY.register("cactus_armor_leggings", () -> new CactusArmorItem.Leggings());
	public static final RegistryObject<Item> CACTUS_ARMOR_BOOTS = REGISTRY.register("cactus_armor_boots", () -> new CactusArmorItem.Boots());
	public static final RegistryObject<Item> NICKEL_ARMOR_HELMET = REGISTRY.register("nickel_armor_helmet", () -> new NickelArmorItem.Helmet());
	public static final RegistryObject<Item> NICKEL_ARMOR_CHESTPLATE = REGISTRY.register("nickel_armor_chestplate", () -> new NickelArmorItem.Chestplate());
	public static final RegistryObject<Item> NICKEL_ARMOR_LEGGINGS = REGISTRY.register("nickel_armor_leggings", () -> new NickelArmorItem.Leggings());
	public static final RegistryObject<Item> NICKEL_ARMOR_BOOTS = REGISTRY.register("nickel_armor_boots", () -> new NickelArmorItem.Boots());
	public static final RegistryObject<Item> CURSED_IRON_ARMOR_HELMET = REGISTRY.register("cursed_iron_armor_helmet", () -> new CursedIronArmorItem.Helmet());
	public static final RegistryObject<Item> CURSED_IRON_ARMOR_CHESTPLATE = REGISTRY.register("cursed_iron_armor_chestplate", () -> new CursedIronArmorItem.Chestplate());
	public static final RegistryObject<Item> CURSED_IRON_ARMOR_LEGGINGS = REGISTRY.register("cursed_iron_armor_leggings", () -> new CursedIronArmorItem.Leggings());
	public static final RegistryObject<Item> CURSED_IRON_ARMOR_BOOTS = REGISTRY.register("cursed_iron_armor_boots", () -> new CursedIronArmorItem.Boots());
	public static final RegistryObject<Item> LAPIS_LAZULI_ARMOR_HELMET = REGISTRY.register("lapis_lazuli_armor_helmet", () -> new LapisLazuliArmorItem.Helmet());
	public static final RegistryObject<Item> LAPIS_LAZULI_ARMOR_CHESTPLATE = REGISTRY.register("lapis_lazuli_armor_chestplate", () -> new LapisLazuliArmorItem.Chestplate());
	public static final RegistryObject<Item> LAPIS_LAZULI_ARMOR_LEGGINGS = REGISTRY.register("lapis_lazuli_armor_leggings", () -> new LapisLazuliArmorItem.Leggings());
	public static final RegistryObject<Item> LAPIS_LAZULI_ARMOR_BOOTS = REGISTRY.register("lapis_lazuli_armor_boots", () -> new LapisLazuliArmorItem.Boots());
	public static final RegistryObject<Item> REDSTONE_ARMOR_HELMET = REGISTRY.register("redstone_armor_helmet", () -> new RedstoneArmorItem.Helmet());
	public static final RegistryObject<Item> REDSTONE_ARMOR_CHESTPLATE = REGISTRY.register("redstone_armor_chestplate", () -> new RedstoneArmorItem.Chestplate());
	public static final RegistryObject<Item> REDSTONE_ARMOR_LEGGINGS = REGISTRY.register("redstone_armor_leggings", () -> new RedstoneArmorItem.Leggings());
	public static final RegistryObject<Item> REDSTONE_ARMOR_BOOTS = REGISTRY.register("redstone_armor_boots", () -> new RedstoneArmorItem.Boots());
	public static final RegistryObject<Item> PRISMARINE_ARMOR_HELMET = REGISTRY.register("prismarine_armor_helmet", () -> new PrismarineArmorItem.Helmet());
	public static final RegistryObject<Item> PRISMARINE_ARMOR_CHESTPLATE = REGISTRY.register("prismarine_armor_chestplate", () -> new PrismarineArmorItem.Chestplate());
	public static final RegistryObject<Item> PRISMARINE_ARMOR_LEGGINGS = REGISTRY.register("prismarine_armor_leggings", () -> new PrismarineArmorItem.Leggings());
	public static final RegistryObject<Item> PRISMARINE_ARMOR_BOOTS = REGISTRY.register("prismarine_armor_boots", () -> new PrismarineArmorItem.Boots());
	public static final RegistryObject<Item> TNT_ARMOR_HELMET = REGISTRY.register("tnt_armor_helmet", () -> new TNTArmorItem.Helmet());
	public static final RegistryObject<Item> TNT_ARMOR_CHESTPLATE = REGISTRY.register("tnt_armor_chestplate", () -> new TNTArmorItem.Chestplate());
	public static final RegistryObject<Item> TNT_ARMOR_LEGGINGS = REGISTRY.register("tnt_armor_leggings", () -> new TNTArmorItem.Leggings());
	public static final RegistryObject<Item> TNT_ARMOR_BOOTS = REGISTRY.register("tnt_armor_boots", () -> new TNTArmorItem.Boots());
	public static final RegistryObject<Item> PLASTIC_ARMOR_HELMET = REGISTRY.register("plastic_armor_helmet", () -> new PlasticArmorItem.Helmet());
	public static final RegistryObject<Item> PLASTIC_ARMOR_CHESTPLATE = REGISTRY.register("plastic_armor_chestplate", () -> new PlasticArmorItem.Chestplate());
	public static final RegistryObject<Item> PLASTIC_ARMOR_LEGGINGS = REGISTRY.register("plastic_armor_leggings", () -> new PlasticArmorItem.Leggings());
	public static final RegistryObject<Item> PLASTIC_ARMOR_BOOTS = REGISTRY.register("plastic_armor_boots", () -> new PlasticArmorItem.Boots());
	public static final RegistryObject<Item> EGGHELL_ARMOR_HELMET = REGISTRY.register("egghell_armor_helmet", () -> new EgghellArmorItem.Helmet());
	public static final RegistryObject<Item> EGGHELL_ARMOR_CHESTPLATE = REGISTRY.register("egghell_armor_chestplate", () -> new EgghellArmorItem.Chestplate());
	public static final RegistryObject<Item> EGGHELL_ARMOR_LEGGINGS = REGISTRY.register("egghell_armor_leggings", () -> new EgghellArmorItem.Leggings());
	public static final RegistryObject<Item> EGGHELL_ARMOR_BOOTS = REGISTRY.register("egghell_armor_boots", () -> new EgghellArmorItem.Boots());
	public static final RegistryObject<Item> GHILLIE_SUIT_HELMET = REGISTRY.register("ghillie_suit_helmet", () -> new GhillieSuitItem.Helmet());
	public static final RegistryObject<Item> GHILLIE_SUIT_CHESTPLATE = REGISTRY.register("ghillie_suit_chestplate", () -> new GhillieSuitItem.Chestplate());
	public static final RegistryObject<Item> GHILLIE_SUIT_LEGGINGS = REGISTRY.register("ghillie_suit_leggings", () -> new GhillieSuitItem.Leggings());
	public static final RegistryObject<Item> GHILLIE_SUIT_BOOTS = REGISTRY.register("ghillie_suit_boots", () -> new GhillieSuitItem.Boots());
	public static final RegistryObject<Item> PLATE_ARMOR_HELMET = REGISTRY.register("plate_armor_helmet", () -> new PlateArmorItem.Helmet());
	public static final RegistryObject<Item> PLATE_ARMOR_CHESTPLATE = REGISTRY.register("plate_armor_chestplate", () -> new PlateArmorItem.Chestplate());
	public static final RegistryObject<Item> CARBON_ARMOR_HELMET = REGISTRY.register("carbon_armor_helmet", () -> new CarbonArmorItem.Helmet());
	public static final RegistryObject<Item> CARBON_ARMOR_CHESTPLATE = REGISTRY.register("carbon_armor_chestplate", () -> new CarbonArmorItem.Chestplate());
	public static final RegistryObject<Item> CARBON_ARMOR_LEGGINGS = REGISTRY.register("carbon_armor_leggings", () -> new CarbonArmorItem.Leggings());
	public static final RegistryObject<Item> CARBON_ARMOR_BOOTS = REGISTRY.register("carbon_armor_boots", () -> new CarbonArmorItem.Boots());
	public static final RegistryObject<Item> CONDENSED_ARMOR_HELMET = REGISTRY.register("condensed_armor_helmet", () -> new CondensedArmorItem.Helmet());
	public static final RegistryObject<Item> CONDENSED_ARMOR_CHESTPLATE = REGISTRY.register("condensed_armor_chestplate", () -> new CondensedArmorItem.Chestplate());
	public static final RegistryObject<Item> CONDENSED_ARMOR_LEGGINGS = REGISTRY.register("condensed_armor_leggings", () -> new CondensedArmorItem.Leggings());
	public static final RegistryObject<Item> CONDENSED_ARMOR_BOOTS = REGISTRY.register("condensed_armor_boots", () -> new CondensedArmorItem.Boots());
	public static final RegistryObject<Item> OBSIDIAN_ARMOR_HELMET = REGISTRY.register("obsidian_armor_helmet", () -> new ObsidianArmorItem.Helmet());
	public static final RegistryObject<Item> OBSIDIAN_ARMOR_CHESTPLATE = REGISTRY.register("obsidian_armor_chestplate", () -> new ObsidianArmorItem.Chestplate());
	public static final RegistryObject<Item> OBSIDIAN_ARMOR_LEGGINGS = REGISTRY.register("obsidian_armor_leggings", () -> new ObsidianArmorItem.Leggings());
	public static final RegistryObject<Item> OBSIDIAN_ARMOR_BOOTS = REGISTRY.register("obsidian_armor_boots", () -> new ObsidianArmorItem.Boots());
	public static final RegistryObject<Item> TITANIUM_ARMOR_HELMET = REGISTRY.register("titanium_armor_helmet", () -> new TitaniumArmorItem.Helmet());
	public static final RegistryObject<Item> TITANIUM_ARMOR_CHESTPLATE = REGISTRY.register("titanium_armor_chestplate", () -> new TitaniumArmorItem.Chestplate());
	public static final RegistryObject<Item> TITANIUM_ARMOR_LEGGINGS = REGISTRY.register("titanium_armor_leggings", () -> new TitaniumArmorItem.Leggings());
	public static final RegistryObject<Item> TITANIUM_ARMOR_BOOTS = REGISTRY.register("titanium_armor_boots", () -> new TitaniumArmorItem.Boots());
	public static final RegistryObject<Item> TUNGSTEN_ARMOR_HELMET = REGISTRY.register("tungsten_armor_helmet", () -> new TungstenArmorItem.Helmet());
	public static final RegistryObject<Item> TUNGSTEN_ARMOR_CHESTPLATE = REGISTRY.register("tungsten_armor_chestplate", () -> new TungstenArmorItem.Chestplate());
	public static final RegistryObject<Item> TUNGSTEN_ARMOR_LEGGINGS = REGISTRY.register("tungsten_armor_leggings", () -> new TungstenArmorItem.Leggings());
	public static final RegistryObject<Item> TUNGSTEN_ARMOR_BOOTS = REGISTRY.register("tungsten_armor_boots", () -> new TungstenArmorItem.Boots());
	public static final RegistryObject<Item> QUIVER_ARMOR_CHESTPLATE = REGISTRY.register("quiver_armor_chestplate", () -> new QuiverItem.Chestplate());
	public static final RegistryObject<Item> QUIVER_ITEM = REGISTRY.register("quiver_item", () -> new QuiverItemItem());
	public static final RegistryObject<Item> DIAMONDSABER = REGISTRY.register("diamondsaber", () -> new DiamondsaberItem());
	public static final RegistryObject<Item> SABER_RED = REGISTRY.register("saber_red", () -> new SaberRedItem());
	public static final RegistryObject<Item> SABER_GREEN = REGISTRY.register("saber_green", () -> new SaberGreenItem());
	public static final RegistryObject<Item> SABER_PURPLE = REGISTRY.register("saber_purple", () -> new SaberPurpleItem());
	public static final RegistryObject<Item> SABER_WHITE = REGISTRY.register("saber_white", () -> new SaberWhiteItem());
	public static final RegistryObject<Item> SABER_YELLOW = REGISTRY.register("saber_yellow", () -> new SaberYellowItem());
	public static final RegistryObject<Item> SABER_ORANGE = REGISTRY.register("saber_orange", () -> new SaberOrangeItem());
	public static final RegistryObject<Item> SABER_DARK = REGISTRY.register("saber_dark", () -> new SaberDarkItem());
	public static final RegistryObject<Item> PLASTIC_SWORD = REGISTRY.register("plastic_sword", () -> new PlasticSwordItem());
	public static final RegistryObject<Item> ICE_SWORD = REGISTRY.register("ice_sword", () -> new IceSwordItem());
	public static final RegistryObject<Item> SANDSTONE_SWORD = REGISTRY.register("sandstone_sword", () -> new SandstoneSwordItem());
	public static final RegistryObject<Item> GLASS_SWORD = REGISTRY.register("glass_sword", () -> new GlassSwordItem());
	public static final RegistryObject<Item> DRUMSTICK = REGISTRY.register("drumstick", () -> new DrumstickItem());
	public static final RegistryObject<Item> COOKED_DRUMSTICK = REGISTRY.register("cooked_drumstick", () -> new CookedDrumstickItem());
	public static final RegistryObject<Item> PLASTIC_CLAYMORE = REGISTRY.register("plastic_claymore", () -> new PlasticClaymoreItem());
	public static final RegistryObject<Item> PLASTIC_BROADSWORD = REGISTRY.register("plastic_broadsword", () -> new PlasticBroadswordItem());
	public static final RegistryObject<Item> PLASTIC_KATANA = REGISTRY.register("plastic_katana", () -> new PlasticKatanaItem());
	public static final RegistryObject<Item> PLASTIC_CUTLASS = REGISTRY.register("plastic_cutlass", () -> new PlasticCutlassItem());
	public static final RegistryObject<Item> PLASTIC_GLAIVE = REGISTRY.register("plastic_glaive", () -> new PlasticGlaiveItem());
	public static final RegistryObject<Item> DAGGER = REGISTRY.register("dagger", () -> new DaggerItem());
	public static final RegistryObject<Item> IRON_SPEAR = REGISTRY.register("iron_spear", () -> new IronSpearItem());
	public static final RegistryObject<Item> WOODEN_BAT = REGISTRY.register("wooden_bat", () -> new WoodenBatItem());
	public static final RegistryObject<Item> MP_POTATO = REGISTRY.register("mp_potato", () -> new MPPotatoItem());
	public static final RegistryObject<Item> BEETZOOKA = REGISTRY.register("beetzooka", () -> new BeetzookaItem());
	public static final RegistryObject<Item> BEETSNIPER = REGISTRY.register("beetsniper", () -> new BeetsniperItem());
	public static final RegistryObject<Item> PRIMAL_DRAGON_SPAWN_EGG = REGISTRY.register("primal_dragon_spawn_egg", () -> new ForgeSpawnEggItem(KraftmineModEntities.PRIMAL_DRAGON, -16777216, -6750055, new Item.Properties().tab(null)));
	public static final RegistryObject<Item> COCONUT_BLOCK = block(KraftmineModBlocks.COCONUT_BLOCK, null);
	public static final RegistryObject<Item> METEORITE = REGISTRY.register("meteorite", () -> new MeteoriteItem());
	public static final RegistryObject<Item> BACKROOM_TRIGGER = block(KraftmineModBlocks.BACKROOM_TRIGGER, null);
	public static final RegistryObject<Item> CLAY_WATER_BOTTLE = REGISTRY.register("clay_water_bottle", () -> new ClayWaterBottleItem());
	public static final RegistryObject<Item> CLAY_MILK_BOTTLE = REGISTRY.register("clay_milk_bottle", () -> new ClayMilkBottleItem());
	public static final RegistryObject<Item> CORN_CROP_0 = block(KraftmineModBlocks.CORN_CROP_0, null);
	public static final RegistryObject<Item> CORN_CROP_1 = block(KraftmineModBlocks.CORN_CROP_1, null);
	public static final RegistryObject<Item> CORN_CROP_2 = block(KraftmineModBlocks.CORN_CROP_2, null);
	public static final RegistryObject<Item> TOMATO_BUSH = block(KraftmineModBlocks.TOMATO_BUSH, null);
	public static final RegistryObject<Item> TOMATO_BUSH_1 = block(KraftmineModBlocks.TOMATO_BUSH_1, null);
	public static final RegistryObject<Item> TOMATO_BUSH_2 = block(KraftmineModBlocks.TOMATO_BUSH_2, null);
	public static final RegistryObject<Item> TOMATO_BUSH_3 = block(KraftmineModBlocks.TOMATO_BUSH_3, null);
	public static final RegistryObject<Item> JOCKEY_TOWER_SPAWN_EGG = REGISTRY.register("jockey_tower_spawn_egg",
			() -> new ForgeSpawnEggItem(KraftmineModEntities.JOCKEY_TOWER, -16751104, -65536, new Item.Properties().tab(KraftmineModTabs.TAB_CRTAB)));
	public static final RegistryObject<Item> ICEWAND_PROJECTILE = REGISTRY.register("icewand_projectile", () -> new IcewandProjectileItem());
	public static final RegistryObject<Item> ICE_WAND = REGISTRY.register("ice_wand", () -> new IceWandItem());
	public static final RegistryObject<Item> LIGHTNING_ROD = REGISTRY.register("lightning_rod", () -> new LightningRodItem());
	public static final RegistryObject<Item> FIRE_SCEPTER = REGISTRY.register("fire_scepter", () -> new FireScepterItem());
	public static final RegistryObject<Item> THE_SWITCHER = REGISTRY.register("the_switcher", () -> new TheSwitcherItem());
	public static final RegistryObject<Item> TOTEM_DYING = REGISTRY.register("totem_dying", () -> new TotemDyingItem());
	public static final RegistryObject<Item> HYDRO_ARMOR_HELMET = REGISTRY.register("hydro_armor_helmet", () -> new HydroArmorItem.Helmet());
	public static final RegistryObject<Item> HYDRO_ARMOR_CHESTPLATE = REGISTRY.register("hydro_armor_chestplate", () -> new HydroArmorItem.Chestplate());
	public static final RegistryObject<Item> HYDRO_ARMOR_LEGGINGS = REGISTRY.register("hydro_armor_leggings", () -> new HydroArmorItem.Leggings());
	public static final RegistryObject<Item> HYDRO_ARMOR_BOOTS = REGISTRY.register("hydro_armor_boots", () -> new HydroArmorItem.Boots());
	public static final RegistryObject<Item> LAVA_ARMOR_HELMET = REGISTRY.register("lava_armor_helmet", () -> new LavaArmorItem.Helmet());
	public static final RegistryObject<Item> LAVA_ARMOR_CHESTPLATE = REGISTRY.register("lava_armor_chestplate", () -> new LavaArmorItem.Chestplate());
	public static final RegistryObject<Item> LAVA_ARMOR_LEGGINGS = REGISTRY.register("lava_armor_leggings", () -> new LavaArmorItem.Leggings());
	public static final RegistryObject<Item> LAVA_ARMOR_BOOTS = REGISTRY.register("lava_armor_boots", () -> new LavaArmorItem.Boots());
	public static final RegistryObject<Item> EXCALIBUR = REGISTRY.register("excalibur", () -> new ExcaliburItem());
	public static final RegistryObject<Item> GIGA_ARMOR_HELMET = REGISTRY.register("giga_armor_helmet", () -> new GigaArmorItem.Helmet());
	public static final RegistryObject<Item> GIGA_ARMOR_CHESTPLATE = REGISTRY.register("giga_armor_chestplate", () -> new GigaArmorItem.Chestplate());
	public static final RegistryObject<Item> GIGA_ARMOR_LEGGINGS = REGISTRY.register("giga_armor_leggings", () -> new GigaArmorItem.Leggings());
	public static final RegistryObject<Item> GIGA_ARMOR_BOOTS = REGISTRY.register("giga_armor_boots", () -> new GigaArmorItem.Boots());
	public static final RegistryObject<Item> IRIS_PURPLE = block(KraftmineModBlocks.IRIS_PURPLE, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> IRIS_SILVER = block(KraftmineModBlocks.IRIS_SILVER, KraftmineModTabs.TAB_CRTAB);
	public static final RegistryObject<Item> GIGA_POTION_X = REGISTRY.register("giga_potion_x", () -> new GigaPotionXItem());
	public static final RegistryObject<Item> CLAY_WATER_BOTTLE_23 = REGISTRY.register("clay_water_bottle_23", () -> new ClayWaterBottle23Item());
	public static final RegistryObject<Item> CLAY_WATER_BOTTLE_13 = REGISTRY.register("clay_water_bottle_13", () -> new ClayWaterBottle13Item());
	public static final RegistryObject<Item> PLASTIC_WATER_BOTTLE = REGISTRY.register("plastic_water_bottle", () -> new PlasticWaterBottleItem());
	public static final RegistryObject<Item> PLASTIC_WATER_BOTTLE_45 = REGISTRY.register("plastic_water_bottle_45", () -> new PlasticWaterBottle45Item());
	public static final RegistryObject<Item> PLASTIC_WATER_BOTTLE_35 = REGISTRY.register("plastic_water_bottle_35", () -> new PlasticWaterBottle35Item());
	public static final RegistryObject<Item> PLASTIC_WATER_BOTTLE_25 = REGISTRY.register("plastic_water_bottle_25", () -> new PlasticWaterBottle25Item());
	public static final RegistryObject<Item> PLASTIC_WATER_BOTTLE_15 = REGISTRY.register("plastic_water_bottle_15", () -> new PlasticWaterBottle15Item());
	public static final RegistryObject<Item> PLASTIC_BOTTLE = REGISTRY.register("plastic_bottle", () -> new PlasticBottleItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
